/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Biblioteca {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public String qualData() {   	
		DateTimeFormatter formatDateTime = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");			
		return LocalDateTime.now().format(formatDateTime);
    }
}
