/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package model;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Biblioteca classUnderTest = new Biblioteca();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
